export const toasterThemes = {
    'top-start': {
        maxToasts: 1,
        containerId: 'top-start',
        containerClass: [
            'fixed',
            'inset-0',
            'pointer-events-none',
            'p-4',
            'flex',
            'flex-col', // top
            'overflow-hidden',
            'z-[200]',
            'items-start', // start
            'gap-2',
            'space-y-3',
        ],
        wrapperClass: [
            'pointer-events-auto',
            'focus:outline-none',
            'rounded',
            'outline-slate-300',
            'outline-offset-2',
            'focus:outline',
            'focus:outline-2',
            'focus-within:outline',
            'focus-within:outline-2',
        ],
        transition: {
            enterActiveClass: 'transition duration-300 ease-out',
            enterFromClass: 'transform -translate-x-full opacity-0',
            enterToClass: 'transform translate-x-0 opacity-100',
            leaveActiveClass: 'transition duration-200 ease-in',
            leaveFromClass: 'transform translate-x-0 opacity-100',
            leaveToClass: 'transform -translate-x-full opacity-0',
        },
    },
    'top-center': {
        maxToasts: 1,
        containerId: 'top-center',
        containerClass: [
            'fixed',
            'inset-0',
            'pointer-events-none',
            'p-4',
            'flex',
            'flex-col', // top
            'overflow-hidden',
            'z-[200]',
            'items-center', // center
            'gap-2',
            'space-y-3',
        ],
        wrapperClass: [
            'pointer-events-auto',
            'focus:outline-none',
            'rounded',
            'outline-slate-300',
            'outline-offset-2',
            'focus:outline',
            'focus:outline-2',
            'focus-within:outline',
            'focus-within:outline-2',
        ],
        transition: {
            enterActiveClass: 'transition duration-300 ease-out',
            enterFromClass: 'transform -translate-y-full opacity-0',
            enterToClass: 'transform translate-y-0 opacity-100',
            leaveActiveClass: 'transition duration-200 ease-in',
            leaveFromClass: 'transform translate-y-0 opacity-100',
            leaveToClass: 'transform -translate-y-full opacity-0',
        },
    },
    'top-end': {
        maxToasts: 1,
        containerId: 'top-end',
        containerClass: [
            'fixed',
            'inset-0',
            'pointer-events-none',
            'p-4',
            'flex',
            'flex-col', // top
            'overflow-hidden',
            'z-[200]',
            'items-end', // end
            'gap-2',
            'space-y-3',
        ],
        wrapperClass: [
            'pointer-events-auto',
            'focus:outline-none',
            'rounded',
            'outline-slate-300',
            'outline-offset-2',
            'focus:outline',
            'focus:outline-2',
            'focus-within:outline',
            'focus-within:outline-2',
        ],
        transition: {
            enterActiveClass: 'transition duration-300 ease-out',
            enterFromClass: 'transform translate-x-full opacity-0',
            enterToClass: 'transform translate-x-0 opacity-100',
            leaveActiveClass: 'transition duration-200 ease-in',
            leaveFromClass: 'transform translate-x-0 opacity-100',
            leaveToClass: 'transform translate-x-full opacity-0',
        },
    },
    'bottom-start': {
        maxToasts: 1,
        containerId: 'bottom-start',
        containerClass: [
            'fixed',
            'inset-0',
            'pointer-events-none',
            'p-4',
            'flex',
            'flex-col-reverse', // bottom
            'overflow-hidden',
            'z-[200]',
            'items-start', // start
            'gap-2',
            'space-y-3',
        ],
        wrapperClass: [
            'pointer-events-auto',
            'focus:outline-none',
            'rounded',
            'outline-slate-300',
            'outline-offset-2',
            'focus:outline',
            'focus:outline-2',
            'focus-within:outline',
            'focus-within:outline-2',
        ],
        transition: {
            enterActiveClass: 'transition duration-300 ease-out',
            enterFromClass: 'transform -translate-x-full opacity-0',
            enterToClass: 'transform translate-x-0 opacity-100',
            leaveActiveClass: 'transition duration-200 ease-in',
            leaveFromClass: 'transform translate-x-0 opacity-100',
            leaveToClass: 'transform -translate-x-full opacity-0',
        },
    },
    'bottom-center': {
        maxToasts: 1,
        containerId: 'bottom-center',
        containerClass: [
            'fixed',
            'inset-0',
            'pointer-events-none',
            'p-4',
            'flex',
            'flex-col-reverse', // bottom
            'overflow-hidden',
            'z-[200]',
            'items-center', // center
            'gap-2',
            'space-y-3',
        ],
        wrapperClass: [
            'pointer-events-auto',
            'focus:outline-none',
            'rounded',
            'outline-slate-300',
            'outline-offset-2',
            'focus:outline',
            'focus:outline-2',
            'focus-within:outline',
            'focus-within:outline-2',
        ],
        transition: {
            enterActiveClass: 'transition duration-300 ease-out',
            enterFromClass: 'transform translate-y-full opacity-0',
            enterToClass: 'transform translate-y-0 opacity-100',
            leaveActiveClass: 'transition duration-200 ease-in',
            leaveFromClass: 'transform translate-y-0 opacity-100',
            leaveToClass: 'transform translate-y-full opacity-0',
        },
    },
    'bottom-end': {
        maxToasts: 1,
        containerId: 'bottom-end',
        containerClass: [
            'fixed',
            'inset-0',
            'pointer-events-none',
            'p-4',
            'flex',
            'flex-col-reverse', // bottom
            'overflow-hidden',
            'z-[200]',
            'items-end', // end
            'gap-2',
            'space-y-3',
        ],
        wrapperClass: [
            'pointer-events-auto',
            'focus:outline-none',
            'rounded',
            'outline-slate-300',
            'outline-offset-2',
            'focus:outline',
            'focus:outline-2',
            'focus-within:outline',
            'focus-within:outline-2',
        ],
        transition: {
            enterActiveClass: 'transition duration-300 ease-out',
            enterFromClass: 'transform translate-x-full opacity-0',
            enterToClass: 'transform translate-x-0 opacity-100',
            leaveActiveClass: 'transition duration-200 ease-in',
            leaveFromClass: 'transform translate-x-0 opacity-100',
            leaveToClass: 'transform translate-x-full opacity-0',
        },
    },
}